# Generated by Django 3.0.8 on 2021-01-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_auto_20210109_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.CharField(max_length=500, verbose_name='card pin number'),
        ),
    ]
