# Generated by Django 3.0.8 on 2021-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0005_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.CharField(max_length=30, verbose_name='deposit/withdrawal time'),
        ),
    ]
